enum SchoolLevel {
  CHILD_EDUCATION_ONE = "CHILD_EDUCATION_ONE",
  CHILD_EDUCATION_TWO = "CHILD_EDUCATION_TWO",
  CHILD_EDUCATION_THREE = "CHILD_EDUCATION_THREE",
  PRE_SCHOOL_ONE = "PRE_SCHOOL_ONE",
  PRE_SCHOOL_TWO = "PRE_SCHOOL_TWO",
  PRE_SCHOOL_THREE = "PRE_SCHOOL_THREE",
  FUNDAMENTAL_ONE = "FUNDAMENTAL_ONE",
  FUNDAMENTAL_TWO = "FUNDAMENTAL_TWO",
  FUNDAMENTAL_THREE = "FUNDAMENTAL_THREE",
  FUNDAMENTAL_FOUR = "FUNDAMENTAL_FOUR",
  FUNDAMENTAL_FIVE = "FUNDAMENTAL_FIVE",
  FUNDAMENTAL_SIX = "FUNDAMENTAL_SIX",
  FUNDAMENTAL_SEVEN = "FUNDAMENTAL_SEVEN",
  FUNDAMENTAL_EIGHT = "FUNDAMENTAL_EIGHT",
  FUNDAMENTAL_NINE = "FUNDAMENTAL_NINE",
  MEDIUM = "MEDIUM",
  GRADUATE = "GRADUATE",
  OTHERS = "Outros",
}

export default SchoolLevel